[project]
protostar-version = "0.8.1"
lib-path = "lib"                           
cairo-path = ["lib"] 

[contracts]


drip_infra_factory = ["lib/morphine/deploymentHelpers/dripInfraFactory.cairo"]
drip_manager = ["lib/morphine/borrowModules/drip/dripManager.cairo"]

drip_transit = ["lib/morphine/borrowModules/drip/dripTransit.cairo"]
drip_configurator = ["lib/morphine/borrowModules/drip/dripConfigurator.cairo"]
drip_configurator_sideline = ["lib/morphine/borrowModules/drip/dripConfiguratorSideline.cairo"]
container = ["lib/morphine/container/container.cairo"]
containerFactory = ["lib/morphine/container/containerFactory.cairo"]
registery = ["lib/morphine/registery.cairo"]
router = ["lib/utils/router.cairo"]

base_adapter = ["lib/morphine/adapters/baseAdapter.cairo"]
erc4626_adapter = ["lib/morphine/adapters/ERC4626/ERC4626.cairo"]
jediswap_adapter = ["lib/morphine/adapters/AMM/jediswap.cairo"]
referral = ["lib/morphine/utils/referral.cairo"]
erc20 = ["lib/openzeppelin/token/erc20/presets/ERC20Mintable.cairo"]
erc4626 = ["tests/mocks/erc4626.cairo"]
faucet = ["lib/utils/faucet.cairo"]
oracle_transit = ["lib/morphine/oracle/oracleTransit.cairo"]
linear_interest_rate_model = ["lib/morphine/pool/interestRateModels/linearInterestRateModel.cairo"]
pool = ["lib/morphine/pool/pool.cairo"]
pool_configurator = ["lib/morphine/pool/poolConfigurator.cairo"]
pass = ["lib/morphine/pass/drip/morphinePass.cairo"]
minter = ["lib/morphine/pass/drip/minter.cairo"]